### ISSUE TITLE
Create a new branch and check switch to new one using tortoisegit

### ISSUE THREAD

**Issue by laura-rodriguez** [thiagotts/show-my-git-branch#1]
When you create a new branch with tortoisegit and check the option to switch to the new one, the label with the current branch is not refreshed.
It might be an improvement instead of an issue.

**Comment by thiagotts** [comment]
Hi Laura. The name of the current branch displayed on the title bar is refreshed every time one out of a specific set of events is triggered by Visual Studio, namely when a solution is opened, when a window within the IDE is activated, when a window within the IDE is created, and when a new document is opened within the IDE. Since switching your current git branch does not trigger any of the aforementioned events, the label is not refreshed. However, if you perform any action that triggers any of these events, the label should be updated.

**Comment by laura-rodriguez** [comment]
Hi Thiago! Thanks for clarify, I will close this issue.
